name: Python package
on: [push]
env:
  ENV_SEC: ${{ secrets.ENV }}
  ENV_VAR: ${{ secrets.ENV_VAR }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print ENV Variables
        run: |
          cd python-demo
          python test.py ${{ env.ENV_SEC }} ${{ env.ENV_VAR }} ${{ secrets.ENV }}

      - name: Run Program
        run: |
          cd python-app
          python test.py
