name: Python package
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print ENV Variables
        env:
          ENV_SEC: ${{ vars.ENV }}
          ENV_VAR: ${{ secrets.ENV_VAR }}
        run: |
          cd python-demo
          python test.py "$ENV_SEC" "$ENV_VAR"